version: '3'
services:
  client:
    container_name: cazadores
    stdin_open: true
    tty: true
    build: ./
    ports: 
      - "3005:3000"
    volumes:
      - ./:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  mysql:
    container_name: cazadores-DB
    image: mysql:8
    platform: linux/amd64
    volumes:
      - cazadoresDB:/var/lib/mysql
    ports: 
      - "3308:3306"
    env_file:
      - ./server/.env
volumes:
  cazadoresDB: